### PR TITLE
add cupy denpendecy

### PR DESCRIPTION
**Pull request by caicre**

### CODE REVIEW

**Comment by isms** [comment]
@caicre Did you want this mered? It shows that you closed the PR.

**Comment by caicre** [comment]
> @caicre Did you want this mered? It shows that you closed the PR.

Yes but I can't merge it because of the following error

CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/pytorch/noarch/repodata.json>

**Comment by isms** [comment]
Where are you seeing that?

**Comment by caicre** [comment]
> Where are you seeing that?

https://github.com/drivendataorg/deid2-runtime/runs/1760448234?check_suite_focus=true
Job: Build, Test, Publish Container (ubuntu-latest, gpu)
Line: 1600, 1614

**Pull request closed without merging**
